### ISSUE TITLE
example connect rpc server with other langague

### ISSUE THREAD

**Issue by medeirosfalante** [jroimartin/rpcmq#7]
I need help to use other programmer language connect in rpcmq server

**Comment by jroimartin** [comment]
rpcmq implements an RPC protocol over AMQP, using json and byte slices to encode the messages:

Message structure:
https://github.com/jroimartin/rpcmq/blob/master/client.go#L48-L51

JSON encoding:
https://github.com/jroimartin/rpcmq/blob/master/client.go#L211-L214

In theory, it should be possible to implement a client in a different language following the reference implementation in Go:

https://github.com/jroimartin/rpcmq/blob/master/client.go
